<?php

/**
 * config.inc of Nesys_at_Home.
 * User: Al_Bundy@breakingcades.info
 * Date: 8/24/2017
 * Time: 10:14 AM
 */

// Database
const MYSQL_USERNAME = 'gc';
const MYSQL_PASSWORD = 'vcbu2eNhc7b37mNMQWSa';
const MYSQL_HOSTNAME = 'localhost';
const MYSQL_PORT = 3306;
const RANKING_2110_DATABASE = '2110_ranking';
const RANKING_2110_CARD = '2110_card';

// Data
const NAVIGATOR_COUNT = 71;
const ITEM_COUNT = 21;
const TITLE_COUNT = 4942;
const AVATAR_COUNT = 294;
const SKIN_COUNT = 21;
const SE_COUNT = 25;
